version: '3.8'

networks:
  kafka-cluster-private:
    driver: overlay
    attachable: true
  kafka-service-public:

volumes:
  zookeeper1-vol:
  kafka1-vol:
  kafka2-vol:
  kafka3-vol:

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181'
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_ENABLE_PROMETHEUS_METRICS=yes
    networks:
      - 'kafka-cluster-private'
    volumes:
       - zookeeper1-vol:/bitnami/zookeeper
       
  kafka1:
    hostname: 'kafka1'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - 'kafka-cluster-private'
    volumes:
       - kafka1-vol:/bitnami/kafka

  kafka2:
    hostname: 'kafka2'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - 'kafka-cluster-private'
    volumes:
       - kafka2-vol:/bitnami/kafka

  kafka3:
    hostname: 'kafka3'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - 'kafka-cluster-private'
    volumes:
       - kafka3-vol:/bitnami/kafka
  
  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    ports:
      - '9000:9000'
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9092,kafka3:9092
    networks:
      - 'kafka-cluster-private'
      - 'kafka-service-public'
