version: '3.8'

networks:
  kafka-cluster:
    driver: bridge

volumes:
  zookeeper1-vol:
  kafka1-vol:
  kafka2-vol:
  kafka3-vol:
  grafana-vol:

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181'
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_ENABLE_PROMETHEUS_METRICS=yes
    networks:
      - kafka-cluster
    volumes:
       - zookeeper1-vol:/bitnami/zookeeper
  kafka1:
    hostname: 'kafka1'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-cluster
    volumes:
       - kafka1-vol:/bitnami/kafka

  kafka2:
    hostname: 'kafka2'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-cluster
    volumes:
       - kafka2-vol:/bitnami/kafka

  kafka3:
    hostname: 'kafka3'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-cluster
    volumes:
       - kafka3-vol:/bitnami/kafka
  
  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    ports:
      - '9000:9000'
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9092,kafka3:9092
    networks:
      - kafka-cluster

  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    depends_on:
     - exporter
    networks:
      - kafka-cluster

  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
    networks:
      - kafka-cluster

  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prom
    networks:
      - kafka-cluster